### PR TITLE
Update beacons.md

### PR DESCRIPTION
**Pull request by UltraSalem**
for yaml rookies like me, the original comment position made it unclear just which text blocks need to be repeated and under which indent. hopefully example is clearer now.

### CODE REVIEW

**Comment by jptrsn** [comment]
I am hesitant to merge this PR, as this project is no longer active. I recommend checking out [espresense](https://espresense.com/) as a replacement - I believe it offers all the functionality as well as quite a few more improvements.

**Comment by maxi1134** [comment]
@UltraSalem I can vouch for ESPresense.

I run it on 11 ESP32s as it is and it works correctly.

It also offers a Triangulation system if you have a lot of ESPs

**Comment by UltraSalem** [comment]
thanks folks. ESPresense is how I found this doco - it seemed to use this page in it's doco, which is why I traced back to here to submit the pull request. The example yaml block on this page: https://espresense.com/home_assistant is this doco here! If it's not actually pulling from this doco though I'll go find somwhere downstream to tap in :)

I'm super keen to learn about the triangulation, but the doco for espresnese is ... mostly missing. It seems to be replaced with youtube videos that gloss over how actually to set everything up. At the risk of derailing his comments section even further, if you can point to any links on triabgulation, I'd be most thankful. I currently just have 2 espresense esp32s set up, one in each key room, tracking my phone for just those rooms, and they're nicely far apart to not need much fine tuning. I have some ideas about how theoretically you could use only two, as long as they were both along one edge of your house. for any given intersection of distances from those two devices, there is only one place they can be. Technically there's two places, but the second one would be outside the house if your ESPs are along the edge of your house, so you can assume the inside one is correct.

**Comment by jptrsn** [comment]
This project is essentially replaced by espresense, I don't believe they're pulling any changes into it from this repo. I do not have any involvement with that project, but I think you should submit the PR to that repo, as it'll be the right place to help users. Sorry I can't be more helpful

**Pull request closed without merging**
